services:
  - type: web
    name: chciai-cz
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_VPS_INSTALL
        value: true
      - key: VPS_HOST
        value: 46.28.111.185
      - key: VPS_USER
        value: root
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
    autoDeploy: true
